config/routes.rb
Rails.application.routes.draw do
  devise_for :workers
  root to: 'salondoors#index'
  resources :salons, only: [:index, :new, :create, :show]
  resources :salons do
    resources :comments, only: [:index, :new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  
  with_options length: { minimum: 1, maximum: 500 } do
    validates :atmosphere
    validates :growth_potential
    validates :gap
    validates :treatment 
    validates :reason_for_retirement 
  end

  belongs to :worker
  belongs to :salon  
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' }, { id: 2, name: '北海道' }, { id: 3, name: '青森県' },
    { id: 4, name: '岩手県' }, { id: 5, name: '宮城県' }, { id: 6, name: '秋田県' },
    { id: 7, name: '山形県' }, { id: 8, name: '福島県' }, { id: 9, name: '茨城県' },
    { id: 10, name: '栃木県' }, { id: 11, name: '群馬県' }, { id: 12, name: '埼玉県' },
    { id: 13, name: '千葉県' }, { id: 14, name: '東京都' }, { id: 15, name: '神奈川県' },
    { id: 16, name: '新潟県' }, { id: 17, name: '富山県' }, { id: 18, name: '石川県' },
    { id: 19, name: '福井県' }, { id: 20, name: '山梨県' }, { id: 21, name: '長野県' },
    { id: 22, name: '岐阜県' }, { id: 23, name: '静岡県' }, { id: 24, name: '愛知県' },
    { id: 25, name: '三重県' }, { id: 26, name: '滋賀県' }, { id: 27, name: '京都府' },
    { id: 28, name: '大阪府' }, { id: 29, name: '兵庫県' }, { id: 30, name: '奈良県' },
    { id: 31, name: '和歌山県' }, { id: 32, name: '鳥取県' }, { id: 33, name: '島根県' },
    { id: 34, name: '岡山県' }, { id: 35, name: '広島県' }, { id: 36, name: '山口県' },
    { id: 37, name: '徳島県' }, { id: 38, name: '香川県' }, { id: 39, name: '愛媛県' },
    { id: 40, name: '高知県' }, { id: 41, name: '福岡県' }, { id: 42, name: '佐賀県' },
    { id: 43, name: '長崎県' }, { id: 44, name: '熊本県' }, { id: 45, name: '大分県' },
    { id: 46, name: '宮崎県' }, { id: 47, name: '鹿児島県' }, { id: 48, name: '沖縄県' }
  ]

  include ActiveHash::Associations
  has_many :salons
end

app/models/salon.rb
class Salon < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :prefecture
  has_one_attached :image
  has_many :comments

  with_options presence: true do
    validates :store_name
    validates :corporate_name
    validates :prefecture_id
    validates :city
    validates :street_number
    validates :station
    validates :established
    validates :offices
  end

  #都道府県
  validates :prefecture_id, numericality: { other_than: 1, message: "can't be blank" }

  #創業年
  validates :established,format: { with: /\A19[0-9]{2}|20[0-9]{2}\z/ }
  validate :established_before_now

  def established_before_now
    return if established.blank?
    errors.add(:established, "は今年以前の西暦を入力してください") if established > Date.today.year
  end

  #店舗数
  validates :offices, numericality: {only_integer: true, greater_than_or_equal_to: 1, message: "店舗数は１以上の数字を入力してください"}
end

app/models/worker.rb
class Worker < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # ニックネーム
  validates :nickname, presence: true

  # パスワード
  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates :password, format: { with: PASSWORD_REGEX, message: 'には6文字以上の半角英数字を使用して設定してください' }, allow_blank: true
  
  has_many :comments,  dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
    @salon = Salon.find(params[:salon_id])
    @comments = @salon.comments
  end
  
  
  def new
    @comment = Comment.new
    @salon = Salon.find(params[:salon_id])
  end

  def create
    @salon = Salon.find(params[:salon_id])
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to salons_path
    else
      render "comments/new"
    end
  end

   private
   
     def comment_params
       params.require(:comment)
       .permit(:atmosphere, :growth_potential, :gap, :treatment, :reason_for_retirement)
       .merge(worker_id: current_worker.id, salon_id: params[:salon_id])
     end
end

app/controllers/salondoors_controller.rb
class SalondoorsController < ApplicationController
  def index
  end
end

app/controllers/salons_controller.rb
class SalonsController < ApplicationController
  def index
    @salons = Salon.order("created_at DESC")
    @comment = Comment.new
  end

  def new
    @salon = Salon.new
  end

  def create
    @salon = Salon.new(salon_params)
    if @salon.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @salon = Salon.find(params[:id])
  end

  private  
  
  def salon_params
    params.require(:salon).permit(:salon_email, :store_name, :corporate_name,
     :prefecture_id, :city, :street_number, :building_name, :station, :established, :offices, :image)
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/salondoors_helper.rb
module SalondoorsHelper
end

app/helpers/salons_helper.rb
module SalonsHelper
end

app/views/comments/index.html.erb
<div class="main">
<div class="main_inner">
  <div class="comment_wrap">

    <div class="detail_header">
      <div class="salon_list_image">
        <% if @salon.image.present?%>
          <%= image_tag @salon.image.variant(gravity: :center, resize:"160x90^", crop:"160x90+0+0").processed , class: "salon-img" if @salon.image.attached?%>
          <% else %>
          <%= image_tag "sample2.JPG" %>
        <% end %>
      </div>
      <div class="detail_title">
        <%= @salon.store_name %>の口コミ一覧
      </div>
    </div>
 
    <div class="comment_list">
      <div class="comment_item">
        雰囲気・環境・働きやすさ
      </div>
      <% @comments.each do |comment| %>
        <ul class="commennt_lists_wrap">
          <li class="commennt_list">
            <div class="comment_list_head">
              <div class="comment_detail">
                <%= comment.atmosphere %>
                <div class="comment_post_date">
                  [投稿日：<%= comment.created_at.strftime('%Y/%m/%d') %>]
                </div>
              </div>
            </div>
          </li>
        </ul>
     <% end %>
    </div>

    <div class="comment_list">
      <div class="comment_item">
        得られた技術、成長できるポイント
      </div>
      <% @comments.each do |comment| %>
        <ul class="commennt_lists_wrap">
          <li class="commennt_list">
            <div class="comment_list_head">
              <div class="comment_detail">
                <%= comment.growth_potential%><div class="comment_post_date">
                  [投稿日：<%= comment.created_at.strftime('%Y/%m/%d') %>]
                </div>
              </div>
            </div>
          </li>
        </ul>
     <% end %>
    </div>

    <div class="comment_list">
      <div class="comment_item">
        入社前後のギャップ
      </div>
      <% @comments.each do |comment| %>
        <ul class="commennt_lists_wrap">
          <li class="commennt_list">
            <div class="comment_list_head">
              <div class="comment_detail">
                <%= comment.gap%>
                <div class="comment_post_date">
                  [投稿日：<%= comment.created_at.strftime('%Y/%m/%d') %>]
                </div>
              </div>
            </div>
          </li>
        </ul>
     <% end %>
    </div>

    <div class="comment_list">
      <div class="comment_item">
        福利厚生・給与など待遇面
      </div>
      <% @comments.each do |comment| %>
        <ul class="commennt_lists_wrap">
          <li class="commennt_list">
            <div class="comment_list_head">
              <div class="comment_detail">
                <%= comment.treatment%>
                <div class="comment_post_date">
                  [投稿日：<%= comment.created_at.strftime('%Y/%m/%d') %>]
                </div>
              </div>
            </div>
          </li>
        </ul>
     <% end %>
    </div>

    <div class="comment_list">
      <div class="comment_item">
        退職した、もしくは退職しようと考えている理由
      </div>
      <% @comments.each do |comment| %>
        <ul class="commennt_lists_wrap">
          <li class="commennt_list">
            <div class="comment_list_head">
              <div class="comment_detail">
                <%= comment.reason_for_retirement%>
                <div class="comment_post_date">
                  [投稿日：<%= comment.created_at.strftime('%Y/%m/%d') %>]
                </div>
              </div>
            </div>
          </li>
        </ul>
     <% end %>
    </div>

app/views/comments/new.html.erb
<div class ="registration-main">
  <div class = "form-wrap">
    <div class ="form-header">
      <h4 class =form-header-text>
      <%= @salon.store_name %>の口コミを投稿する</h2>
    </div>

<%#= ログインしているユーザーにのみ表示%>
    <% if worker_signed_in? %>
    <div class="form-group">
      <%= form_with model: [@salon, @comment],local: true do |f|%>
      <%= render 'shared/error_messages', model: f.object %>

      <div class="form-text-wrap ">
        <div class="form-text">
          <%= f.label :atmosphere , "雰囲気・環境・働きやすさ" %>
          <span class="required">必須</span>
        </div>
          <%=f.text_area :atmosphere, placeholder:"500文字以内で記入してください", class:"comments-text"%>
      </div>

      <div class="form-text-wrap ">
        <div class="form-text">
          <%= f.label :growth_potential  , "得られた技術、成長できるポイント" %>
          <span class="required">必須</span>
        </div>
          <%=f.text_area :growth_potential, placeholder:"500文字以内で記入してください", class:"comments-text"%>
      </div>

      <div class="form-text-wrap ">
        <div class="form-text">
          <%= f.label :gap , "入社前後のギャップ" %>
          <span class="required">必須</span>
        </div>
          <%= f.text_area :gap, placeholder:"500文字以内で記入してください", class:"comments-text"%>
      </div>

      <div class="form-text-wrap ">
        <div class="form-text">
          <%= f.label :treatment  , "福利厚生・給与など待遇面"%>
          <span class="required">必須</span>
        </div>
          <%= f.text_area :treatment , placeholder:"500文字以内で記入してください", class:"comments-text"%>
      </div>

      <div class="form-text-wrap ">
        <div class="form-text">
          <%= f.label :reason_for_retirement, "退職した、退職しようと考えている理由" %>
          <span class="required">必須</span>
        </div>
          <%= f.text_area :reason_for_retirement, placeholder:"500文字以内で記入してください", class:"comments-text"%>
      </div>

      <div class="login-btn ">
        <%= f.submit "保存する", class: "login-red-btn"%>
      </div>
      <% end %>
    </div>

<% else %>
  <strong><p>※※※ 口コミの投稿にはログインが必要です ※※※</p></strong>
  ▶︎<%= link_to 'ログイン', worker_session_path, class: "login" %>
  ▶︎<%= link_to '新規登録', new_worker_registration_path, class: "sign-up" %>
<% end %>
  </div>
</div>

   

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Salondoor1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%# リセットCSSの設定 %>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <%# CSS・・・assets/stylesheets/.css %>
  <div class="container">

  <div class="Head_header">
  <header>
    <div class="Head_inner">
      <div class="Head_box_first">
        <div class="Head_logo">
          <%= link_to image_tag("salondoor_logo2.PNG",size: "192x71"), "/"%>
        </div>
      </div>
          
      <% if worker_signed_in? %>
      <div class="Head_box_second">

        <div class="Head_box_second1">
          <div id='Head_btn'>
            <ul>
              <li><%= link_to current_worker.nickname, "#", class: "Headlink_btn" %></li>
              <li><%= link_to "ログアウト", destroy_worker_session_path, method: :delete, class: "Headlink_btn"%></li>
            </ul>
          </div>
        </div>
      </div>
       
      <% else %>
      <div class="Head_box_second"> 
        <div class="Head_box_second1">
          <div id='Head_btn'>
          <ul>
              <li><%= link_to 'ログイン', worker_session_path, class: "Headlink_btn" %></li>
              <li><%= link_to '新規登録', new_worker_registration_path, class: "Headlink_btn" %></li>
            </ul>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </header>
  </div>
  
  
  

  <body>
    <%= yield %>
  </body>


  <div class="Foot_footer">
  <footer class>
    <div class="Foot_logo">
      <%= link_to image_tag("salondoor_logo2.PNG",size: "115x42"), "/"%>
    </div>
    
    <div class="Foot_List">
      <ul>
        <li class="Foot_ListItem"><%= link_to '利用規約', "/" %></li>
        <li class="Foot_ListItem"><%= link_to 'プライバシーポリシー', "/" %></li>
        <li class="Foot_ListItem"><%= link_to 'ヘルプ', "/" %></li>
        <li class="Foot_ListItem"><%= link_to 'サイトマップ', "/" %></li>
      </ul>
    </div>
    <div class="Foot_copyright">
      Copyright © SALONDOOR All rights reserved.
    </div>
  </footer>
  </div>
  </div>

</div>
</html>

app/views/salondoors/index.html.erb
<div class="top">
  <div class="top_inner">

  <div class="top_image_text">
    <div class="top_image1">
      <%= link_to image_tag("salondoor_top.PNG"), "/"%>
    </div>
    
    <div class="top_text1">
      自分に合ったサロンが見つかる
    </div>
  </div>

  <div class="top_menu">
  
   <div class="top_menu_list">
      <h1 class=top_menu_text>サロンの口コミを投稿する</h1>
      <% if worker_signed_in? %>
      <div class="menu_link">
        <div id="menu_link_btn">
          <ul>
           <li><%= link_to 'サロン一覧', salons_path, class: "link_btn" %></li>
          </ul>
        </div>
      </div>
      <% else %>
      <div class="menu_link">
        <div id="menu_link_btn">
          <ul>
            <li><%= link_to 'ログイン', worker_session_path, class: "link_btn" %></li>
            <li><%= link_to '新規登録', new_worker_registration_path, class: "link_btn" %></li>
          </ul>
        </div>
      </div>
      <% end %>
    </div>
 

    <div class="top_menu_list">
      <h1 class=top_menu_text>サロンの口コミを見る</h1>
      <div class="menu_link">
        <div id="menu_link_btn">
          <ul>
           <li><%= link_to 'サロン一覧', salons_path, class: "link_btn" %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="top_menu_list">
      <h1 class=top_menu_text>サロン情報を登録する</h1>
      <div class="menu_link">
        <div id="menu_link_btn">
          <ul>
            <li><%= link_to 'サロン登録', new_salon_path, class: "link_btn" %></li>
          </ul>
        </div>
      </div>
    </div>
     
  </div>

  </div>
</div>

app/views/salons/index.html.erb
<div class="main">
  <div class="main_inner">
  <h2>ネイルサロン一覧</h2>
   
    <div class="">
    </div>

    <% @salons.each do |salon| %>
    <ul class="salon_lists_wrap">
      <li class="salon_list">
        <div class="salon_list_head">
          <div class="salon_name">
            <%= link_to salon.store_name, salon_comments_path(salon.id) %>
            <div class="salon_detail">
            <%= link_to 'サロン詳細', root_path, class: "detail_btn" %></div>
          </div>
        </div>

        <div class="salon_list_body">
          <div class="salon_list_image">
           <% if salon.image.present?%>
            <%= image_tag salon.image.variant(gravity: :center, resize:"400x225^", crop:"400x225+0+0").processed , class: "salon-img" if salon.image.attached?%>
            <% else %>
           <%= image_tag "sample.JPG" %>
           <% end %>
          </div>
          <div class="salon_list_contents">
            <div class="salon_list_info">
              アクセス：<%= salon.prefecture.name%><%= salon.city %>(<%= salon.station %>)
            </div>
            <div id="salon_list_comments">
              <ul>
               <li><%= link_to '口コミを見る', salon_comments_path(salon.id), class: "comment_link_btn" %></li>
            <li><%= link_to '口コミを投稿する',  new_salon_comment_path(salon.id), class: "comment_link_btn" %></li>
            </ul>
            </div>
          </div>
        </div>
      </li>
    </ul>
    <% end %>


  </div>
</div>

app/views/salons/new.html.erb
<div class ="registration-main">
  <div class = "form-wrap">

    <div class ="form-header">
      <h2 class =form-header-text>サロン情報作成</h2>
    </div>

    <div class="form-group">
      <%= form_with(model: @salon, local: true) do |f|%>
      <%= render 'shared/error_messages', model: f.object %>

      <div class="form-text-wrap ">
        <div class="form-text">
          <%= f.label :store_name , "店名" %>
          <span class="required">必須</span>
        </div>
        <%=f.text_field :store_name, class:"input-default"%>
      </div>

      <div class="form-text-wrap ">
        <div class="form-text">
          <%= f.label :corporate_name  , "法人名" %>
          <span class="required">必須</span>
        </div>
        <%=f.text_field :corporate_name, class:"input-default" %>
      </div>

      <div class="form-text-wrap ">
        <div class="form-text">
          <%= f.label :prefecture_id , "勤務地（都道府県）" %>
          <span class="required">必須</span>
        </div>
        <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"input-default", id:"prefecture"}) %>
      </div>

      <div class="form-text-wrap ">
        <div class="form-text">
          <%= f.label :city , "勤務地（市町村）" %>
          <span class="required">必須</span>
        </div>
        <%= f.text_field :city, placeholder:"例）横浜市緑区", class:"input-default"%>
      </div>

      <div class="form-text-wrap ">
        <div class="form-text">
          <%= f.label :street_number , "勤務地（番地）" %>
          <span class="required">必須</span>
        </div>
        <%= f.text_field :street_number, placeholder:"例）青山1-1-1", class:"input-default"%>
      </div>

      <div class="form-text-wrap ">
        <div class="form-text">
          <%= f.label :building_name , "勤務地（ビル名）" %>
          <%= f.text_field :building_name, placeholder:"例）柳ビル103", class:"input-default"%>
        </div>
      </div>

      <div class="form-text-wrap ">
        <div class="form-text">
          <%= f.label :station , "勤務地(最寄駅)" %>
          <span class="required">必須</span>
        </div>
        <%= f.text_field :station, placeholder:"例）横浜駅 徒歩1分・吉祥寺駅からバス15分", class:"input-default"%>
      </div>

      <div class="form-text-wrap ">
        <div class="form-text">
          <%= f.label :established , "創業年(西暦)" %>
          <span class="required">必須</span>
          </div>
        <%= f.text_field :established, placeholder:"例）2000", class:"input-default"%>
      </div>

      <div class="form-text-wrap ">
        <div class="form-text">
          <%= f.label :offices , "店舗数" %>
          <span class="required">必須</span>
        </div>
        <%= f.text_field :offices, placeholder:"例）5", class:"input-default"%>
      </div>

      <div class="form-text-wrap ">
        <div class="form-text">
          <%= f.label :image, "お店の雰囲気がわかる写真" %><br />
        </div>
        <%= f.file_field :image, id:"salon_image" %>
      </div>

      <div class="login-btn ">
        <%= f.submit "保存する", class: "login-red-btn"%>
      </div>
      <% end %>

    </div>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>